# Generated by Django 2.1.3 on 2019-01-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebarchivesweb', '0002_auto_20181224_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('other', 'Other')], max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='media',
            field=models.ManyToManyField(blank=True, to='ebarchivesweb.Media'),
        ),
    ]
