# Generated by Django 2.1.4 on 2019-01-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebarchivesweb', '0005_auto_20190106_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='type',
            field=models.CharField(choices=[('talk', 'Talk/Conference/Panel'), ('event', 'Event'), ('festival', 'Festival'), ('misc', 'Misc'), ('radio', 'Radio'), ('residence', 'Residence'), ('workshop', 'Workshop'), ('exhibit', 'Exhibit')], max_length=200),
        ),
    ]
