# Generated by Django 2.1.3 on 2019-01-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebarchivesweb', '0006_auto_20190106_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
