# Generated by Django 2.1.3 on 2019-01-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebarchivesweb', '0007_event_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
