# Generated by Django 2.1.3 on 2019-01-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebarchivesweb', '0008_artist_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
