# Generated by Django 2.1.3 on 2019-01-08 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebarchivesweb', '0009_auto_20190108_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='recurring_event',
        ),
        migrations.AddField(
            model_name='event',
            name='recurring_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebarchivesweb.RecurringEvent'),
        ),
    ]
