# Generated by Django 2.1.7 on 2019-05-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebarchivesweb', '0010_auto_20190108_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='type',
            field=models.CharField(choices=[('talk', 'Talk/Conference/Panel'), ('event', 'Event'), ('collaboration', 'Collaboration'), ('misc', 'Misc'), ('radio', 'Radio'), ('residence', 'Residence'), ('workshop', 'Workshop'), ('exhibition', 'Exhibitions')], max_length=200),
        ),
    ]
