# Generated by Django 2.1.7 on 2019-05-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebarchivesweb', '0011_auto_20190509_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='type',
            field=models.CharField(choices=[('talk', 'Talk/Conference/Panel'), ('event', 'Event'), ('collaboration', 'Collaboration'), ('salon_data', 'Data : Salon'), ('sight_sound', 'Sight & Sound'), ('meetup', 'Meet-up'), ('radio', 'Radio'), ('residence', 'Residence'), ('workshop', 'Workshop'), ('exhibition', 'Exhibition')], max_length=200),
        ),
    ]
